PackageName: "SolverCore"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "ff4d7338-4cf1-434d-91df-b86cb86fb843"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "v0.13.0"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
