PackageName: "SolverCore"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "ff4d7338-4cf1-434d-91df-b86cb86fb843"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "7bcc7d0a2905be7ca9d1dd6519e8df59ae89605c"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
AddCirrusCI: true
